### ISSUE TITLE
Can only update every second instead of 100ms

### ISSUE THREAD

**Issue by IsakL** [MathieuRelmy/SR2_Telemetry#1]
![pic for bug](https://user-images.githubusercontent.com/117126526/209717007-9e4cd922-da15-4e07-a87d-ba92bdc72e14.png)
![image](https://user-images.githubusercontent.com/117126526/209717015-9842b2fe-fabe-4c14-8210-5263e859ab1d.png)
It has the wait on 0.1 but it only updates every second anyway

**Comment by MathieuRelmy** [comment]
![image](https://user-images.githubusercontent.com/60399897/209719846-dca05093-fe85-44a0-8222-c5f1a8da7c16.png)

did you make sure the sampling frequency is under 1000 on your telemetry box? the rate on the box is in milliseconds by the way.

**Comment by IsakL** [comment]
ohhh

**Comment by IsakL** [comment]
works, thank you

**Comment by MathieuRelmy** [comment]
All right, i will now close the issue.
